### ISSUE TITLE
how to use in "SPA"

### ISSUE THREAD

**Issue by natocTo** [felixhagspiel/jsOnlyLightbox#19]
Hello, is there way how to "destroy" loaded lightbox?
I have single page app with routing. I need load() lightbox on every page without refreshing page.

It is probably very bad practise but now I removing thumbnail array in lightbox object and push new items via thumbnail.push. But I lost navigation arrays (next, previous) in lightbox.

**Comment by felixhagspiel** [comment]
sorry for the late reply. You can try setting `var lightbox;` and on every pageload you do `lightbox = new Lightbox();`. Does that help?

**Comment by natocTo** [comment]
I tried a lot of options and now I have one working good for me.
Now I am using once lightbox.load() and then in nested views lightbox.thumbnails.push(img), lightbox.open(false, 'group') and when I changing view lightbox.thumbnails = []

**Comment by felixhagspiel** [comment]
perfect!
