### ISSUE TITLE
ToDos

### ISSUE THREAD

**Issue by felixhagspiel** [felixhagspiel/jsOnlyLightbox#2]
- [x] limit max-width/height of images due to original file-size to prevent bad resolution
- [x] add loading-GIF
- [x] fix too big image size when resizing window to fullscreen https://github.com/felixhagspiel/jsOnlyLightbox#lightboxopensrc-link
- [x] fix prev/next button position on load
- [ ] add HTML support
- [ ] add touch/swipe support
- [x] fix IE8 http://screencast.com/t/20o6pqvXHz
- [x] add caption
- [x] click on image shows next image - option
- [x] only init controls if more than 1 image
- [x] chrome on iOS bug prevents correct display of images
- [x] add pure JS/CSS loading-animation & control-arrows instead of gif/png`s
- [ ] add Slideshow
- [x] add broken link support / fix loading animation
- [x] remove constant modifiers for image size

**Comment by K4T** [comment]
Hi! Any chance to support broken links to images? Now user will see spinner which will never dissapear if link to image is broken..

**Comment by felixhagspiel** [comment]
hey @K4T I will try to implement it next week. Thanks for the suggestion!

**Comment by K4T** [comment]
Hi, thank you. I have one more request for you. Can you add ability to modify values of those 0.8 factors, which are here: https://github.com/felixhagspiel/jsOnlyLightbox/blob/master/js/lightbox.js#L649.
For my project I would like to use values like 0.9 or 0.95 because I have to use as much space as possible for my images in lightbox. I dont like to modify source code of plugins, it is a bad practice as we all know.

**Comment by felixhagspiel** [comment]
@K4T I added a maxImgSize modifier and an onloaderror-callback to the options, see [here]( https://github.com/felixhagspiel/jsOnlyLightbox/tree/development#onloaderror-functionevent) and [here](https://github.com/felixhagspiel/jsOnlyLightbox/tree/development#maximgsize-float).
be sure to take the [latest version from the dev-branch](https://github.com/felixhagspiel/jsOnlyLightbox/tree/development) and not the master. And please report any errors here, so I can fix them before merging into master.
Does that fix your problems?

**Comment by K4T** [comment]
Hi! maxImgSize works like it should. Nice! But I have problem with onloaderror method which is NOT called when link to image is broken. Here is my code:

```js
var lightbox = new Lightbox();
            lightbox.load({
                maxImgSize: 0.95,
                onloaderrror: function() {
                    console.log('404!')
                }
            });
```

**Comment by felixhagspiel** [comment]
@K4T maybe because there is an 'r' in error too much? :)

**Comment by K4T** [comment]
Yeah, sorry for that stupid mistake.
