### ISSUE TITLE
Add video support

### ISSUE THREAD

**Issue by pachacamac** [felixhagspiel/jsOnlyLightbox#26]
I have images and videos (with automatically created thumbnail GIFs) in my current gallery. I am adding your lightbox as an optional addon and would like to keep the videos working. Any chance/idea how to do that? I'm happy to help too.

**Comment by felixhagspiel** [comment]
well first of all there has to be some sort of detection if the content which should be loaded is an image or html content. then  the next question is where that content comes from, if you provide ID`s which link to hidden containers which are then loaded, or if you load them dynamically. Unfortunately I have no time at all atm, but if you provide a pull-requests or if you got any questions I will try to help. there is also already an issue here: https://github.com/felixhagspiel/jsOnlyLightbox/issues/7
