### ISSUE TITLE
Setting animation option to false doesn't work

### ISSUE THREAD

**Issue by rmilecki** [felixhagspiel/jsOnlyLightbox#27]
Documentation quote:
> Passing false disables the animation.

However doing `lightbox.load({animation: false});` doesn't work. Lightbox still uses 400ms animation.

This is caused by the following part of code:
`animation: opt.animation || 400,`
which picks 400 number value in case of passing false.

I believe above line should be changed to:
`animation: typeof opt.animation === 'number' || opt.animation === false ? opt.animation : 400,`

Proposed code treats `false` as disabled animation, `true` as default animation time (400 ms) and any numeric value as custom animation time.

**Comment by rmilecki** [comment]
[0001-Fix-support-for-setting-animation-option-to-false.txt](https://github.com/felixhagspiel/jsOnlyLightbox/files/149629/0001-Fix-support-for-setting-animation-option-to-false.txt)

**Comment by felixhagspiel** [comment]
totally right. Thanks!
