### ISSUE TITLE
Same image with same name twice is not working

### ISSUE THREAD

**Issue by revelon** [felixhagspiel/jsOnlyLightbox#30]
For some reason, when there are two identical images (and with identical caption), it is not possible to navigate further, for example there: https://uloz.to/soubory/Dalin/kamaradky-kamaradi/
Edge case, but still, perhaps worth fixing...

**Comment by felixhagspiel** [comment]
Unfortunately this is related to this line of code: https://github.com/felixhagspiel/jsOnlyLightbox/blob/master/js/lightbox.js#L246

A solution would be to add numbers at initialization of the box. I will look into that
